name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy with deploy-pages
        uses: actions/deploy-pages@v2
        with:
          build_dir: .  # Projenin kök dizinindeki index.html vs. alınarak direkt deploy edilir
