name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Ana branch'te değişiklik olduğunda çalıştır

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./  # Eğer dosyalar dist içindeyse ./dist yap

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages  # Doğru artifact ismi kullanılıyor mu?
