name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # veya hangi branch'ı kullanıyorsan

permissions:
  contents: read
  pages: write
  id-token: write  # ✅ Bunu ekledik!

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: .  # Eğer index.html ana dizindeyse

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v2
